on:
  push:
    branches:
      - develop
  pull_request:
      types: [opened, synchronize, reopened]
name: Analyze
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Get develop
      run: git fetch origin develop
    - name: Install dependencies
      run: npm ci
    - name: Run tests
      run: npm test -- --watchAll=false
    - name: Fix absolute paths
      shell: bash
      run: |
        sed -i 's+/home/runner/work/expiry-util/expiry-util+/github/workspace+g' coverage/lcov.info
    - name: SonarCloud scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
